apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: invary-maat-controller-cluster-role-binding
  namespace: invary
subjects:
- kind: ServiceAccount
  name: invary-maat-controller
  namespace: invary
roleRef:
  kind: ClusterRole
  name: invary-maat-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
