apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: invary
  name: invary-maat-controller-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/status"]
  verbs: ["get", "list", "watch", "patch"]
